
stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-dotnet-code:       # Build worker code.
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:7.0
  variables:
    NUGET_PACKAGES: "/builds/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/worker/.nuget/packages"   # Change nuget packages path 
  cache:
    key: ${CI_COMMIT_REF_SLUG}            # Isolated cache for each branch
    paths:
      - worker/.nuget/packages/**         # Save restored packages (Nuget)
  script:
    - echo "Compiling the code..."
    - cd worker
    - dotnet restore
    - dotnet publish -c Release -o publish --self-contained false
    - echo "Compile complete."
  artifacts:
    paths:
      - worker/publish/
  only:
    - Development
    - main
    - tags

test-dontnet-code:   # Test worker code.
  stage: test        # It only starts when the job in the build stage completes successfully.
  image: mcr.microsoft.com/dotnet/sdk:7.0
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - cd worker
    - dotnet test  --logger "trx;LogFileName=TestResults/Dotnet-TestResults_$(date +%s).trx"      # Test the code and save the testing results.
  only:
    - Development
    - main
    - tags

test-flask-code:   # Test vote code.
  stage: test      
  image: python:3.11-slim
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - cd vote
    - pip install -r requirements.txt
    - pip install flake8 pytest
    - flake8 .
    - pytest 
  only:
    - prepare
    - Development
    - main
    - tags

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  only:
    - Development
    - main
    - tags
